### PR TITLE
implemented grabScreenshot (android)

### PR DESCRIPTION
**Pull request by nickolanack**
this returns a promise with an ImageSource object

### CODE REVIEW

**Comment by nickolanack** [comment]
I'm wondering if the ios version should also return a promise with an ImageSource. I believe it currently returns an ios native UIIMage

**Comment by EddyVerbruggen** [comment]
You're absolutely right, it should return a similar type as you've done here. Would you like to amend this PR? Otherwise, I can do it as well of course.

**Comment by nickolanack** [comment]
I'll amend (shortly)

**Comment by EddyVerbruggen** [comment]
Awesome, thanks!

**Comment by EddyVerbruggen** [comment]
I've tested it (added a call to the [demo app](/demo)) and it works beautifully!

Note that I've renamed the screengrab implementation file because my IDE tried to resolve `screengrab.ts` at compile time. Since it's an Android-specific file I didn't bother adding an `screengrab.d.ts` (with a declaration of the `FragmentScreenGrab` class).

**Comment by nickolanack** [comment]
Cool. I'm not sure what the proper naming/organization strategy of files so apologies if I make a mess of that.

**Comment by EddyVerbruggen** [comment]
Ha, I get that. It can be a bit confusing. As long as you don't mind me refactoring little things I'd say: keep 'em coming! 💪

**Pull request merged**
