### PR TITLE
Add video for ios and android

### PR DESCRIPTION
**Pull request by nickolanack**
Here is an implementation of ar.addVideo. allows adding 2d video panels in in ar space. 
they automatically play, and loop.
```js
ar.addVideo({
    position:{
      x: 0,
      y: 0.5
      z: -1
    },
    video:"https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_5mb.mp4"
});
```

the ios version is modified version of your ARImageTrackingActions 
the android version is modified version of the google sample  ChromaKey Video (https://developers.google.com/ar/develop/java/sceneform/samples) - with green-screen part disabled (** this would be cool to implement for ios too though!)

I have not figured out how to provide audio in ios
This node type should probably expose play, pause, etc methods

works with urls and files in assets folder

added demo

* Android version requires VideoPlane.sfb in assets - I'm not sure how to include this as part of the library, but added it to the demo

### CODE REVIEW

**Comment by nickolanack** [comment]
IMG_0021

**Comment by EddyVerbruggen** [comment]
@nickolanack What the ****! This is delightful 😍

I just ran the demo app on iOS and the audio is working great actually. Perhaps you had your device on mute or something. Didn't try Android yet, but this is epic stuff mate!

**Comment by EddyVerbruggen** [comment]
@nickolanack Android works great as well! I've moved `VideoPlane.sfb` to the `src/platforms/android/assets` folder so it gets merged nicely during a build and we can avoid having to ask users to bundle it with their app if they need it. It's only a small file so I don't see any harm in doing it this way.

**Comment by EddyVerbruggen** [comment]
@nickolanack I've added play/pause/isPlaying to both platforms, and it seems to work great! I've hooked it up to the `onTap` function [in the demo](https://github.com/EddyVerbruggen/nativescript-ar/blob/1576c7e2b61830468795540a9b62083ffc1e51b1/demo/app/main-page.ts#L355-L362) so you can check it out if you like.

**Comment by nickolanack** [comment]
Oh awesome!

**Pull request merged**
