### PR TITLE
IOS size uiview using nativescript measure and anchor to bottom

### PR DESCRIPTION
**Pull request by nickolanack**
and properly anchor to bottom to match android
add initial rotation to behave like original SCNPlane (not require initial rotation)

### CODE REVIEW

**Comment by nickolanack** [comment]
Image-1 (1)

**Comment by EddyVerbruggen** [comment]
That's super nice!

I noticed the UI Views on iOS are a bit compressed vertically and I think it's because the screenratio (on my iPhone X) is roughly 2.15 (height/width), but the AR camera view is 1.33 so I think measuring the view height needs to be compensated a little for the difference.

So that's why I just added this and it seems to work quite nicely indeed:

https://github.com/EddyVerbruggen/nativescript-ar/blob/93f54a58fd5b1e86789edb73153528841149f881/src/nodes/ios/aruiview.ts#L45-L48

**Comment by nickolanack** [comment]
Oh - That’s great!. I noticed that too and added the 0.04m but hopefully that can be removed now

**Comment by EddyVerbruggen** [comment]
@nickolanack I was wondering what that 0.04 was for. I just removed it and it looks pretty great to me :)

**Pull request merged**
