### PR TITLE
Android use .imgdb if found in folder (defined by trackingImagesBundle) 

### PR DESCRIPTION
**Pull request by nickolanack**
If no .imgdb is found then reads all images in folder (current behavior) but also read Contents.json files and use defined width

removed hardcoded scaling factor from android.ts 

provide image width/height to ARTrackingImageDetectedEventData and add method `addNode` in ARImageTrackingActions

update ar.trackImage to accept width and name properties 

regenerated video plane .sfb file for sceneform 1.12.0 (was crashing android for me) renamed to video_chroma.sfb

### CODE REVIEW

**Comment by nickolanack** [comment]
#66

**Comment by nickolanack** [comment]
I also added images.imgdb into PokemonResources!! this file will need to be regenerated if new images are added... (it is not necessary to include the .jpg files at all since they are embedded in .imgdb )

**Comment by EddyVerbruggen** [comment]
This is brilliant! Image detection works so. much. better! with this PR merged. Great work!

**Comment by EddyVerbruggen** [comment]
Btw, can you explain to me how that `video_chroma.sfb` file was generated (and why we need it), so I can explain it to others if I ever need to (and generate one myself)?

**Comment by nickolanack** [comment]
@EddyVerbruggen Re:  can you explain to me how that video_chroma.sfb file was generated (and why we need it)... 

Yup.
The video player `addVideo` and `playVideo` methods require that model/material, to render video onto a plane. I took video_chroma.sfb from the google sample https://github.com/google-ar/sceneform-android-sdk/tree/master/samples/chromakeyvideo which atm uses sceneform 1.10.0, - I also updated that project to use 1.12.0 and it crashed the underlying Filament Engine (version mismatch) but was fixed by reimporting the .obj and .mat source files (also included in that sample lib) - future versions of sceneform/filament may require updating the .sfb  again -(because [it seems to me that] sceneform does not  intend to be backward compatible with sfb models)

To regenerate this sfb in android studio right click on the .obj file and choose import sceneform asset, also select the .mat file and output to /res/raw (there are better/generic instructions for this in other places) source obj and mat are here https://github.com/google-ar/sceneform-android-sdk/tree/master/samples/chromakeyvideo/app/sampledata/models

The important thing about this model is the material, which includes an external texture source and can be set programatically using ExternalTexture and MediaPlayer.  This model/material also has a chromaKey option but is unused. 
https://github.com/EddyVerbruggen/nativescript-ar/blob/eb690b8dd30f87707c1e86009781d241138fb8ff/src/nodes/android/arvideo.ts#L56
https://github.com/EddyVerbruggen/nativescript-ar/blob/eb690b8dd30f87707c1e86009781d241138fb8ff/src/nodes/android/arvideo.ts#L58
https://github.com/EddyVerbruggen/nativescript-ar/blob/eb690b8dd30f87707c1e86009781d241138fb8ff/src/nodes/android/arvideo.ts#L90-L91

It should be possible to generate this same model/material using a gltf file so that might be worth looking into since .sfb is only done with android studio afaik.

Right now creating materials in sceneform is **difficult/messy**, the current strategy seems to be some variation of:  package a low poly model and material as a .sfb (or gltf). To use the material,  load the model, extract it's material component, and apply it to other object (well the video just uses the model geometry since it is always a plane...) ~ But anyway I have faith that sceneform will provide a much simpler way to create materials (planes would be nice too), and all this can be greatly simplified...

**Comment by nickolanack** [comment]
The material 
https://github.com/google-ar/sceneform-android-sdk/blob/72eb6b386aed2abf93cc9da4aab35009a938897b/samples/chromakeyvideo/app/sampledata/models/chroma_key_video_material.mat#L14-L45

has named parameters: `videoTexture`, `keyColor`, `disableChromaKey`

Originally I was going to strip out the chromaKey part of the material, But I also thought it would be cool to actually support chroma keyed videos at some point so it would just need to be re-enabled

**Comment by nickolanack** [comment]
the other thing about this model that is slightly annoying is that its origin is at the bottom center of the model, (like a character model) so it needed to be adjusted vertically to be consistent with ios
https://github.com/EddyVerbruggen/nativescript-ar/blob/eb690b8dd30f87707c1e86009781d241138fb8ff/src/nodes/android/arvideo.ts#L7-L12

**Pull request merged**
