### PR TITLE
Support lookAt* methods

### PR DESCRIPTION
**Pull request by nickolanack**
add arcommon node methods:
getPosition
getWorldPosition

lookAtWorldPosition
lookAtPosition (local ~less usefull)
lookAtNode (ARCommonNode)

add ar method:
getCameraPosition

update solar system demo:
control panel `view.lookAtWorldPosition(ar.getCameraPosition());`

### CODE REVIEW

**Comment by EddyVerbruggen** [comment]
Amazing! This will be super useful :)

**Comment by EddyVerbruggen** [comment]
@nickolanack It seems like the solarsystem demo has the sliders in the control panel reversed. Check out that demo on Android for instance.. perhaps it needs to be flipped?

**Comment by nickolanack** [comment]
@EddyVerbruggen Ohhh -  I remember thinking this might be an issue for IOS
https://developer.apple.com/documentation/scenekit/scnplane?language=objc
...The surface is one-sided. Its surface normal vectors point in the positive z-axis direction of its local coordinate space...

**Comment by nickolanack** [comment]
also it is set to render double sided but the back side is reversed...

**Comment by nickolanack** [comment]
is this ios specific issue or android as well?

**Comment by EddyVerbruggen** [comment]
They behave a bit differently; on iOS the card is flipped (text is 'mirrored') but the sliders move the correct way (although they don't have an effect, but that's a different issue). On Android the card doesn't _appear_ to be flipped, but when dragging a slider to the right it actually moves to the left, so I think it's flipped as well.

**Comment by nickolanack** [comment]
I'm just testing android - but looks like i was definitely facing android in the opposite direction

**Pull request merged**
