### PR TITLE
implements startRecordingVideo/stopRecordingVideo (android)

### PR DESCRIPTION
**Pull request by nickolanack**
this requires permission to write to external files system (android.permission.WRITE_EXTERNAL_STORAGE) but does [not] make the request. I'm not sure if is something that it should do or be left to the user. thoughts?

### CODE REVIEW

**Comment by EddyVerbruggen** [comment]
I think the plugin should take care of that (JIT when the record feature is invoked). Would you like me to handle the code for it? I've done it before a few times.

**Comment by nickolanack** [comment]
I'd appreciate it if you added it! thanks! I am a bit reluctant, because I know there are backward compatibility issues with androidX support

**Comment by EddyVerbruggen** [comment]
No worries, I'll take care of it tomorrow. 👍

**Comment by EddyVerbruggen** [comment]
Done.

**Pull request merged**
