### PR TITLE
Updated to latest Nativescript

### PR DESCRIPTION
**Pull request by Emanuele-Fortunati**
Hi @EddyVerbruggen 
I know you have spoken to Katrina about updating the plugin: I've done the update as you asked and this is the PR.

A couple of notes:
1. I've also updated the demo apps, but I haven't fully tested them
2. I have not updated the docs
3. In the plugin file ar.android.ts I had to comment out a function on line 563 because a TS error. Surely there's a solution to it, but I've run out of time and couldn't fix it. Perhaps you can easily as you know the plugin well ;)

Let me know if you need anything.

Regards,

Emanuele

### CODE REVIEW

**Comment by EddyVerbruggen** [comment]
Thanks @Emanuele-Fortunati - did you test your changes with your app? So if I would publish this as-is, you would be happy?

I'm not feeling comfortable because after updating the demo app it crashes on iOS when tapping a detected surface, and the other apps haven't been tested either.

So I could release a 'beta' version, but not a real 2.0.

**Comment by Emanuele-Fortunati** [comment]
@EddyVerbruggen Yes I did some testing but not fully to be fair. I've you release a beta it would be fine for me and any bug I'd spot I'll collect them in a new PR. I think in that way we would have a faster release eventually. My main concern is not the plugin anyway is the iOS APIs as quite a few things have changed, but hopefully not too many changes to be done on ur end.
Please let me know if you release the beta so I can integrate it and test more :)

**Comment by EddyVerbruggen** [comment]
@Emanuele-Fortunati I just realised: you have the plugin repo locally so you can go to /publish (in the root) en run `.pack.sh` - this will produce the same targball as you'd get from npm - you can then link to that file from your project on the local filesystem.

Here's an example from a different project:

```json
    "nativescript-sumup": "file:../plugins/nativescript-sumup/src/nativescript-sumup-1.0.0.tgz",
```

**Comment by Emanuele-Fortunati** [comment]
Oh true @EddyVerbruggen dunno why I havent consider that option. We'll do the tests that way, it's even faster. Thanks

**Pull request merged**
