### PR TITLE
implemented addSphere  (android)

### PR DESCRIPTION
**Pull request by nickolanack**
this implements addSphere.
some things that may want to be reviewed:
 - positioned items relative to a shared origin anchor and position items locally on init
 - exposed fragment getFragment() (for testing)
 - added optional parentNode for add*

### CODE REVIEW

**Comment by EddyVerbruggen** [comment]
Cool! Let me review this tomorrow.

Regarding `getFragment`: I don't mind at all, but earlier today I added `args.android` [here](https://github.com/EddyVerbruggen/nativescript-ar/blob/b0e78404e974e97e7276e6640c175644394f7ae6/demo/app/main-page.ts#L41) which would also get you the fragment. Great minds think alike, I guess ;)

**Comment by nickolanack** [comment]
Fyi: The first 2 commit messages are no longer applicable since I replaced my fork with your master branch

**Comment by nickolanack** [comment]
I'm going to create a branch and implement addTube/addCylinder just to get familiar with ts. I'll pr that as well later (low hanging fruit)

**Comment by EddyVerbruggen** [comment]
Hi @nickolanack, awesome work, really clean readable code! Please go ahead with other PRs 💪

If you want some feedback (because you mentioned you're learning TypeScript) then I have one remark: Try to avoid using the `function` keyword, because it breaks one of the nicer TS features; when using the arrow syntax (`() =>`) instead, the context of `this` will transfer into the function. No more `that = this` assignments needed. Check my last commit (which refers this issue) for an example.

Btw, would you mind changing your IDE settings for this project so it doesn't reformat indentation? That would help creating even smaller PRs.

**Comment by nickolanack** [comment]
great. thanks for the feedback.

**Pull request merged**
